/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DatingCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MSG_FEE"
      | "SWIPE_FEE"
      | "chatKeys"
      | "collectedFees"
      | "deactivateProfile"
      | "getInterests"
      | "isMatched"
      | "matches"
      | "owner"
      | "profiles"
      | "registerProfile"
      | "sendMessage"
      | "storeChatKey"
      | "swipe"
      | "swipes"
      | "withdrawFees"
      | "zkVerifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesWithdrawn"
      | "MatchFound"
      | "MessageSent"
      | "ProfileRegistered"
      | "SwipeRecorded"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MSG_FEE", values?: undefined): string;
  encodeFunctionData(functionFragment: "SWIPE_FEE", values?: undefined): string;
  encodeFunctionData(functionFragment: "chatKeys", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "collectedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInterests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMatched",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "matches", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProfile",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeChatKey",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swipe",
    values: [AddressLike, boolean, BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "swipes",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "zkVerifier",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "MSG_FEE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SWIPE_FEE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "chatKeys", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInterests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMatched", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeChatKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swipe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swipes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zkVerifier", data: BytesLike): Result;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchFoundEvent {
  export type InputTuple = [
    userA: AddressLike,
    userB: AddressLike,
    pairHash: BytesLike
  ];
  export type OutputTuple = [userA: string, userB: string, pairHash: string];
  export interface OutputObject {
    userA: string;
    userB: string;
    pairHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageSentEvent {
  export type InputTuple = [
    sender: AddressLike,
    recipient: AddressLike,
    feePaid: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    recipient: string,
    feePaid: bigint
  ];
  export interface OutputObject {
    sender: string;
    recipient: string;
    feePaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileRegisteredEvent {
  export type InputTuple = [user: AddressLike, encryptedHash: BytesLike];
  export type OutputTuple = [user: string, encryptedHash: string];
  export interface OutputObject {
    user: string;
    encryptedHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwipeRecordedEvent {
  export type InputTuple = [
    swiper: AddressLike,
    target: AddressLike,
    liked: boolean
  ];
  export type OutputTuple = [swiper: string, target: string, liked: boolean];
  export interface OutputObject {
    swiper: string;
    target: string;
    liked: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DatingCore extends BaseContract {
  connect(runner?: ContractRunner | null): DatingCore;
  waitForDeployment(): Promise<this>;

  interface: DatingCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MSG_FEE: TypedContractMethod<[], [bigint], "view">;

  SWIPE_FEE: TypedContractMethod<[], [bigint], "view">;

  chatKeys: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  collectedFees: TypedContractMethod<[], [bigint], "view">;

  deactivateProfile: TypedContractMethod<[], [void], "nonpayable">;

  getInterests: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  isMatched: TypedContractMethod<
    [a: AddressLike, b: AddressLike],
    [boolean],
    "view"
  >;

  matches: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  profiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint] & {
        encryptedHash: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  registerProfile: TypedContractMethod<
    [encryptedHash: BytesLike, interests: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  sendMessage: TypedContractMethod<[recipient: AddressLike], [void], "payable">;

  storeChatKey: TypedContractMethod<
    [partner: AddressLike, encKey: BytesLike],
    [void],
    "nonpayable"
  >;

  swipe: TypedContractMethod<
    [
      target: AddressLike,
      liked: boolean,
      proof: BytesLike,
      publicSignals: BigNumberish[]
    ],
    [void],
    "payable"
  >;

  swipes: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  withdrawFees: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  zkVerifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MSG_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SWIPE_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "chatKeys"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "collectedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivateProfile"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getInterests"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isMatched"
  ): TypedContractMethod<[a: AddressLike, b: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint] & {
        encryptedHash: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProfile"
  ): TypedContractMethod<
    [encryptedHash: BytesLike, interests: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendMessage"
  ): TypedContractMethod<[recipient: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "storeChatKey"
  ): TypedContractMethod<
    [partner: AddressLike, encKey: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swipe"
  ): TypedContractMethod<
    [
      target: AddressLike,
      liked: boolean,
      proof: BytesLike,
      publicSignals: BigNumberish[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "swipes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "zkVerifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MatchFound"
  ): TypedContractEvent<
    MatchFoundEvent.InputTuple,
    MatchFoundEvent.OutputTuple,
    MatchFoundEvent.OutputObject
  >;
  getEvent(
    key: "MessageSent"
  ): TypedContractEvent<
    MessageSentEvent.InputTuple,
    MessageSentEvent.OutputTuple,
    MessageSentEvent.OutputObject
  >;
  getEvent(
    key: "ProfileRegistered"
  ): TypedContractEvent<
    ProfileRegisteredEvent.InputTuple,
    ProfileRegisteredEvent.OutputTuple,
    ProfileRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SwipeRecorded"
  ): TypedContractEvent<
    SwipeRecordedEvent.InputTuple,
    SwipeRecordedEvent.OutputTuple,
    SwipeRecordedEvent.OutputObject
  >;

  filters: {
    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "MatchFound(address,address,bytes32)": TypedContractEvent<
      MatchFoundEvent.InputTuple,
      MatchFoundEvent.OutputTuple,
      MatchFoundEvent.OutputObject
    >;
    MatchFound: TypedContractEvent<
      MatchFoundEvent.InputTuple,
      MatchFoundEvent.OutputTuple,
      MatchFoundEvent.OutputObject
    >;

    "MessageSent(address,address,uint256)": TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
    MessageSent: TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;

    "ProfileRegistered(address,bytes32)": TypedContractEvent<
      ProfileRegisteredEvent.InputTuple,
      ProfileRegisteredEvent.OutputTuple,
      ProfileRegisteredEvent.OutputObject
    >;
    ProfileRegistered: TypedContractEvent<
      ProfileRegisteredEvent.InputTuple,
      ProfileRegisteredEvent.OutputTuple,
      ProfileRegisteredEvent.OutputObject
    >;

    "SwipeRecorded(address,address,bool)": TypedContractEvent<
      SwipeRecordedEvent.InputTuple,
      SwipeRecordedEvent.OutputTuple,
      SwipeRecordedEvent.OutputObject
    >;
    SwipeRecorded: TypedContractEvent<
      SwipeRecordedEvent.InputTuple,
      SwipeRecordedEvent.OutputTuple,
      SwipeRecordedEvent.OutputObject
    >;
  };
}
