/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EscrowContent {
  export type ListingStruct = {
    creator: AddressLike;
    contentHash: BytesLike;
    price: BigNumberish;
    active: boolean;
    lockedAt: BigNumberish;
  };

  export type ListingStructOutput = [
    creator: string,
    contentHash: string,
    price: bigint,
    active: boolean,
    lockedAt: bigint
  ] & {
    creator: string;
    contentHash: string;
    price: bigint;
    active: boolean;
    lockedAt: bigint;
  };
}

export interface EscrowContentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LOCK_DURATION"
      | "PROTOCOL_FEE_BPS"
      | "cancelListing"
      | "collectedFees"
      | "getListing"
      | "hasUnlocked"
      | "listContent"
      | "listings"
      | "nextListingId"
      | "owner"
      | "unlockContent"
      | "unlocked"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContentListed"
      | "ContentUnlocked"
      | "ListingCancelled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUnlocked",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listContent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextListingId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unlockContent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlocked",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "LOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasUnlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextListingId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unlockContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace ContentListedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    creator: AddressLike,
    price: BigNumberish,
    contentHash: BytesLike
  ];
  export type OutputTuple = [
    listingId: bigint,
    creator: string,
    price: bigint,
    contentHash: string
  ];
  export interface OutputObject {
    listingId: bigint;
    creator: string;
    price: bigint;
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContentUnlockedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    buyer: AddressLike,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    buyer: string,
    creator: string,
    amount: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    buyer: string;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingCancelledEvent {
  export type InputTuple = [listingId: BigNumberish];
  export type OutputTuple = [listingId: bigint];
  export interface OutputObject {
    listingId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowContent extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowContent;
  waitForDeployment(): Promise<this>;

  interface: EscrowContentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  PROTOCOL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  cancelListing: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  collectedFees: TypedContractMethod<[], [bigint], "view">;

  getListing: TypedContractMethod<
    [listingId: BigNumberish],
    [EscrowContent.ListingStructOutput],
    "view"
  >;

  hasUnlocked: TypedContractMethod<
    [listingId: BigNumberish, buyer: AddressLike],
    [boolean],
    "view"
  >;

  listContent: TypedContractMethod<
    [contentHash: BytesLike, price: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, bigint] & {
        creator: string;
        contentHash: string;
        price: bigint;
        active: boolean;
        lockedAt: bigint;
      }
    ],
    "view"
  >;

  nextListingId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  unlockContent: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "payable"
  >;

  unlocked: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  withdrawFees: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelListing"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [listingId: BigNumberish],
    [EscrowContent.ListingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUnlocked"
  ): TypedContractMethod<
    [listingId: BigNumberish, buyer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "listContent"
  ): TypedContractMethod<
    [contentHash: BytesLike, price: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, bigint] & {
        creator: string;
        contentHash: string;
        price: bigint;
        active: boolean;
        lockedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextListingId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unlockContent"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "unlocked"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ContentListed"
  ): TypedContractEvent<
    ContentListedEvent.InputTuple,
    ContentListedEvent.OutputTuple,
    ContentListedEvent.OutputObject
  >;
  getEvent(
    key: "ContentUnlocked"
  ): TypedContractEvent<
    ContentUnlockedEvent.InputTuple,
    ContentUnlockedEvent.OutputTuple,
    ContentUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "ListingCancelled"
  ): TypedContractEvent<
    ListingCancelledEvent.InputTuple,
    ListingCancelledEvent.OutputTuple,
    ListingCancelledEvent.OutputObject
  >;

  filters: {
    "ContentListed(uint256,address,uint256,bytes32)": TypedContractEvent<
      ContentListedEvent.InputTuple,
      ContentListedEvent.OutputTuple,
      ContentListedEvent.OutputObject
    >;
    ContentListed: TypedContractEvent<
      ContentListedEvent.InputTuple,
      ContentListedEvent.OutputTuple,
      ContentListedEvent.OutputObject
    >;

    "ContentUnlocked(uint256,address,address,uint256)": TypedContractEvent<
      ContentUnlockedEvent.InputTuple,
      ContentUnlockedEvent.OutputTuple,
      ContentUnlockedEvent.OutputObject
    >;
    ContentUnlocked: TypedContractEvent<
      ContentUnlockedEvent.InputTuple,
      ContentUnlockedEvent.OutputTuple,
      ContentUnlockedEvent.OutputObject
    >;

    "ListingCancelled(uint256)": TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;
    ListingCancelled: TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;
  };
}
