/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DatingCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DatingCore__factory>;
    getContractFactory(
      name: "EscrowContent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EscrowContent__factory>;
    getContractFactory(
      name: "MockZKVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockZKVerifier__factory>;

    getContractAt(
      name: "DatingCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DatingCore>;
    getContractAt(
      name: "EscrowContent",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EscrowContent>;
    getContractAt(
      name: "MockZKVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockZKVerifier>;

    deployContract(
      name: "DatingCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DatingCore>;
    deployContract(
      name: "EscrowContent",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowContent>;
    deployContract(
      name: "MockZKVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockZKVerifier>;

    deployContract(
      name: "DatingCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DatingCore>;
    deployContract(
      name: "EscrowContent",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowContent>;
    deployContract(
      name: "MockZKVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockZKVerifier>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
