// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title MockZKVerifier
 * @notice Stub ZK-proof verifier for demo purposes.
 *         Interface mirrors a real SnarkJS-generated Groth16 verifier,
 *         so it can be swapped in production with zero changes to callers.
 *
 * @dev In production replace this contract with the verifier generated by:
 *      snarkjs groth16 exportsolidityverifier circuit.zkey verifier.sol
 */
contract MockZKVerifier {
    event ProofVerified(address indexed prover, bool result);

    /**
     * @notice Verifies a ZK proof.
     * @param proof     Encoded proof bytes (a, b, c points in Groth16)
     * @param publicSignals Array of public signals (ageValid, interestOverlap)
     * @return True if proof is considered valid
     *
     * Mock logic: returns true if proof is non-empty and
     *             publicSignals[0] == 1 (ageValid) and
     *             publicSignals[1] >= 1 (at least one interest overlap).
     */
    function verifyProof(
        bytes calldata proof,
        uint256[] calldata publicSignals
    ) external returns (bool) {
        bool result = (
            proof.length > 0 &&
            publicSignals.length >= 2 &&
            publicSignals[0] == 1 &&   // ageValid
            publicSignals[1] >= 1      // interestOverlap
        );
        emit ProofVerified(msg.sender, result);
        return result;
    }

    /**
     * @notice Convenience view version (no event) for off-chain checks.
     */
    function verifyProofView(
        bytes calldata proof,
        uint256[] calldata publicSignals
    ) external pure returns (bool) {
        return (
            proof.length > 0 &&
            publicSignals.length >= 2 &&
            publicSignals[0] == 1 &&
            publicSignals[1] >= 1
        );
    }
}
